### PR TITLE
Feature: Groups!

### PR DESCRIPTION
**Pull request by dawnerd**
Groups can now be added by either the API or a text file.

API example:

``` javascript
var urls = [
    {
      group: 'Circles',
      url: 'http://leanin.org/circles/'
    },
    {
      group: 'Circles',
      url: 'http://leanin.org/circle-login/'
    },
    {
      group: 'Circles',
      url: 'http://leanin.org/circle-faqs/'
    },
    'http://leanin.org',
    {
      url: 'http://leanin.org/team/'
    },
    {
      group: 'News+Inspiration',
      url: 'http://leanin.org/news-inspiration/'
    },
  ];

var shot = new Screenshot(urls, options);
```

Text file:

```
http://leanin.org

Homepage
http://leanin.org/about/

News+Inspiration
http://leanin.org/news-inspiration/
```

This branch also contains the imagick switcheroo.

### CODE REVIEW

**Comment by jgallen23** [comment]
getting this error:

```
./bin/multishot -f example/urls.txt -o .
Capturing screenshots. This might take a while.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

**Comment by jgallen23** [comment]
now getting this error: 

```
[jga@Gregs-Mac-mini.local] ~/code/multishot [feature/groups]: ./bin/multishot -f example/urls.txt -o .
Capturing screenshots. This might take a while.
Generating frame for: http://leanin.org
Generating frame for: http://leanin.org/about/
Generating frame for: http://leanin.org/news-inspiration/
Generating label: http://leanin.org
Generating label: http://leanin.org/about/
Adding spacing to label: http://leanin.org
Adding spacing to label: http://leanin.org/about/
Generating label: http://leanin.org/news-inspiration/
Chopping off bottom padding: http://leanin.org
Chopping off bottom padding: http://leanin.org/about/
Placing label: http://leanin.org
Placing label: http://leanin.org/about/
Adding spacing to label: http://leanin.org/news-inspiration/
Chopping off bottom padding: http://leanin.org/news-inspiration/
Finished labeling screenshot: http://leanin.org
Finished labeling screenshot: http://leanin.org/about/
Placing label: http://leanin.org/news-inspiration/
WriteBlob Failed `Default/2013918-combined.png' @ error/png.c/MagickPNGErrorHandler/1804

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at EventEmitter.emit (events.js:74:15)
    at EventEmitter.<anonymous> (/Users/jga/code/multishot/lib/screenshot-service.js:244:14)
```

**Comment by dawnerd** [comment]
Thats odd considering it got that far down processing. Almost sounds like either a file got moved during that time or maybe it ran out of memory. Could you give it a shot with just two urls?

**Comment by jgallen23** [comment]
Same with two:

```
[jga@Gregs-Mac-mini.local] ~/code/multishot [feature/groups]: ./bin/multishot -f example/urls.txt -o .
Capturing screenshots. This might take a while.
Generating frame for: http://leanin.org
Generating frame for: http://leanin.org/about/
Generating label: http://leanin.org/about/
Adding spacing to label: http://leanin.org/about/
Generating label: http://leanin.org
Chopping off bottom padding: http://leanin.org/about/
Adding spacing to label: http://leanin.org
Placing label: http://leanin.org/about/
Chopping off bottom padding: http://leanin.org
Placing label: http://leanin.org
Finished labeling screenshot: http://leanin.org/about/
Finished labeling screenshot: http://leanin.org
WriteBlob Failed `Homepage/2013919-combined.png' @ error/png.c/MagickPNGErrorHandler/1804

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at EventEmitter.emit (events.js:74:15)
    at EventEmitter.<anonymous> (/Users/jga/code/multishot/lib/screenshot-service.js:244:14)
```

**Comment by dawnerd** [comment]
Can you look in the temp directory and see if any of the images are corrupt? Might be the actual screenshots.

**Comment by jgallen23** [comment]
files in the tmp directory look good.  Even the labels look good.

**Comment by dawnerd** [comment]
Now part of #10

**Pull request closed without merging**
