### PR TITLE
HTML renderer

### PR DESCRIPTION
**Pull request by dawnerd**
Needs some css love but otherwise functional.

### CODE REVIEW

**Comment by dawnerd** [comment]
Ignore the older commits, this was branched off the old "new" imagick branch.

**Comment by jgallen23** [comment]
man, this is awesome!  so fast!

**Comment by jgallen23** [comment]
I'm all for moving forward with this technique if you are

**Comment by dawnerd** [comment]
Same, such a good idea to do it this way. Plus... custom render templates! its not in the readme, but you can pass in -tpl "somefile.html"

**Comment by jgallen23** [comment]
awesome. lets merge this in, release and update the grunt plugin

**Comment by jgallen23** [comment]
also, I'd release this as 0.1.0

**Pull request merged**
